name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build project
      run: |
        xcodebuild -project LearnSwift.xcodeproj \
                   -scheme LearnSwift \
                   -configuration Release \
                   -destination 'platform=macOS' \
                   build
                   
    - name: Archive app (optional)
      run: |
        xcodebuild -project LearnSwift.xcodeproj \
                   -scheme LearnSwift \
                   -configuration Release \
                   -destination 'platform=macOS' \
                   archive -archivePath ./build/LearnSwift.xcarchive
                   
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LearnSwift-Build
        path: ./build/LearnSwift.xcarchive